name: Commit
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
      - uses: actions/checkout@master

      - name: GitHub Package Registry
        uses: ohioit/action-kaniko@multi-image-support
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          image: kaniko
          cache: true
          cache_registry: cache

